### ISSUE TITLE
Unhandled exception: Instance of 'BuildException'

### ISSUE THREAD

**Issue by mafreud** [shorebirdtech/shorebird#1022]
**Description**
I got an error when I try to patch.

**Steps To Reproduce**

1. shorebird release ios-alpha --force
2. upload ipa to FAD
3. run shorebird patch

```
⠴ Building release... (128.4s)Unhandled exception:
Instance of 'BuildException'
#0      ShorebirdBuildMixin.buildIpa (package:shorebird_cli/src/shorebird_build_mixin.dart:205:7)
<asynchronous suspension>
#1      PatchIosCommand.run (package:shorebird_cli/src/commands/patch/patch_ios_command.dart:106:7)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#3      ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/command_runner.dart:151:18)
<asynchronous suspension>
#4      ShorebirdCliCommandRunner.run (package:shorebird_cli/src/command_runner.dart:93:14)
<asynchronous suspension>
#5      main (file:///Users/masahiroaoki/.shorebird/packages/shorebird_cli/bin/shorebird.dart:24:5)
<asynchronous suspension>
```

**Shorebird Version**
```
❯ shorebird --version
Shorebird 0.11.2
Shorebird Engine • revision 655974aed33b608d1075cffae0fcaf06772d90d8
```

**Comment by mafreud** [comment]
I updated shorebird to 0.12.1, but the bug still exists.

### shorebird version
```
❯ shorebird --version
Shorebird 0.12.1
Shorebird Engine • revision bf07ad7b0b777cb9aff15e59bf928504857f4ada
```
### error
```
❯ shorebird patch ios-alpha
[WARN] iOS support is alpha. See https://docs.shorebird.dev/status#ios-alpha for more information.
✓ Fetching apps (1.4s)
✓ Fetching releases (0.5s)
Which release would you like to patch? 1.15.0+145
✓ Fetching ipa artifact (0.3s)
⠴ Building release... (152.4s)Unhandled exception:
Instance of 'BuildException'
#0      ShorebirdBuildMixin.buildIpa (package:shorebird_cli/src/shorebird_build_mixin.dart:208:7)
<asynchronous suspension>
#1      PatchIosCommand.run (package:shorebird_cli/src/commands/patch/patch_ios_command.dart:163:7)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#3      ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/command_runner.dart:151:18)
<asynchronous suspension>
#4      ShorebirdCliCommandRunner.run (package:shorebird_cli/src/command_runner.dart:93:14)
<asynchronous suspension>
#5      main (file:///Users/masahiroaoki/.shorebird/packages/shorebird_cli/bin/shorebird.dart:28:5)
<asynchronous suspension>
```

**Comment by mafreud** [comment]
@felangel Thank you!
