### ISSUE TITLE
fix: `shorebird preview` should detect/warn when targeting x86 devices

### ISSUE THREAD

**Issue by joelc0193** [shorebirdtech/shorebird#1173]
**Description**

When I do `shorebird preview` the app that gets installed crashes everytime I open it. But my app runs fine when I run it on debug mode directly from VSCode.

**Expected Behavior**

The app installed via `shorebird preview` should run the same as when I run the app in debug mode through VSCode.

**Additional Context**

Output of `shorebird preview`:

(base) Joels-MBP:sdk jcastro2$ shorebird preview
✓ Fetching apps (0.2s)
Which app would you like to preview? st_james_park_app
✓ Fetching releases (69ms)
Which release would you like to preview? 2.0.0+2
Which platform would you like to preview? android
✓ Extracting metadata (0.4s)
✓ Installing apks (6.1s)
✓ Starting app (0.7s)
--------- beginning of kernel

--------- beginning of main

--------- beginning of system

--------- beginning of crash

08-27 18:39:26.287  5674  5723 I flutter : The Dart VM service is listening on http://127.0.0.1:37009/jkKEvrd8g6w=/

**Comment by eseidel** [comment]
That sure is unexpected.  🤔

**Comment by eseidel** [comment]
Does `adb logcat` show more information about the crash?

**Comment by joelc0193** [comment]
Here is the output from the moment I open the app:

08-27 21:41:07.100   986   986 D TaplEvents: Main / Touch event: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=691.9629, y[0]=1830.8838, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x1, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=3370167, downTime=3370167, deviceId=11, source=0x5002, displayId=0 }
08-27 21:41:07.182   986   986 D TaplEvents: Main / Touch event: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=691.9629, y[0]=1830.8838, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x1, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=3370250, downTime=3370167, deviceId=11, source=0x5002, displayId=0 }
08-27 21:41:07.195   986   986 D TaplEvents: Main / start: startAppShortcutOrInfoActivity
08-27 21:41:07.198   515   599 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.gmail.joelc0193.st_james_park_app/.MainActivity bnds=[585,1648][854,2056]} from uid 10137
08-27 21:41:07.199   515   536 D EventSequenceValidator: inc AccIntentStartedEvents to 2
08-27 21:41:07.211   515  5401 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
08-27 21:41:07.211   515  5401 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
08-27 21:41:07.216   415   415 I perfetto: ing_service_impl.cc:758 Configured tracing session 49, #sources:1, duration:5000 ms, #buffers:1, total buffer size:4096 KB, total sessions:1, uid:1071 session name: ""
08-27 21:41:07.219   515   515 W ActivityManager: Unable to start service Intent { act=android.service.appprediction.AppPredictionService cmp=com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiPredictionService } U=0: not found
08-27 21:41:07.219   515   515 W RemoteAppPredictionService: could not bind to Intent { act=android.service.appprediction.AppPredictionService cmp=com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiPredictionService } using flags 67108865
08-27 21:41:07.226   406   406 I perfetto: probes_producer.cc:230  Ftrace setup (target_buf=49)
08-27 21:41:07.237   515   536 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10164; state: DISABLED
08-27 21:41:07.238   515   543 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10164; state: ENABLED
08-27 21:41:07.257   306   351 D goldfish-address-space: claimShared: Ask to claim region [0x3e6613000 0x3e76c6000]
08-27 21:41:07.371   383   456 D AF::Track: interceptBuffer: took 5862us to intercept 0 tracks
08-27 21:41:07.381   290   290 D Zygote  : Forked child process 9265
08-27 21:41:07.388   515   599 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
08-27 21:41:07.393   515   543 W ActivityManager: Slow operation: 157ms so far, now at startProcess: returned from zygote!
08-27 21:41:07.397   406   406 I perfetto: ftrace_procfs.cc:176    enabled ftrace
08-27 21:41:07.377     0     0 W perfetto: enabled ftrace
08-27 21:41:07.404   515   543 W ActivityManager: Slow operation: 158ms so far, now at startProcess: done updating battery stats
08-27 21:41:07.404   515   543 W ActivityManager: Slow operation: 168ms so far, now at startProcess: building log message
08-27 21:41:07.404   515   543 I ActivityManager: Start proc 9265:com.gmail.joelc0193.st_james_park_app/u0a164 for pre-top-activity {com.gmail.joelc0193.st_james_park_app/com.gmail.joelc0193.st_james_park_app.MainActivity}
08-27 21:41:07.404   515   543 W ActivityManager: Slow operation: 169ms so far, now at startProcess: starting to update pids map
08-27 21:41:07.406   515   543 W ActivityManager: Slow operation: 170ms so far, now at startProcess: done updating pids map
08-27 21:41:07.434  9265  9265 W _james_park_ap: Unexpected CPU variant for X86 using defaults: x86
08-27 21:41:07.449   387   411 I adbd    : jdwp connection from 9265
08-27 21:41:07.468   515   599 W InputReader: Device virtio_input_multi_touch_10 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.468   515   599 W InputReader: Device virtio_input_multi_touch_4 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.468   515   599 W InputReader: Device virtio_input_multi_touch_11 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.468   515   599 W InputReader: Device virtio_input_multi_touch_9 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.468   515   599 W InputReader: Device virtio_input_multi_touch_7 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.468   515   599 W InputReader: Device virtio_input_multi_touch_5 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.468   515   599 W InputReader: Device virtio_input_multi_touch_2 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.468   515   599 W InputReader: Device virtio_input_multi_touch_6 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.468   515   599 W InputReader: Device virtio_input_multi_touch_3 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.468   515   599 W InputReader: Device virtio_input_multi_touch_8 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.469   515   599 W InputReader: Device virtio_input_multi_touch_10 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.469   515   599 W InputReader: Device virtio_input_multi_touch_4 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.469   515   599 W InputReader: Device virtio_input_multi_touch_11 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.469   515   599 W InputReader: Device virtio_input_multi_touch_9 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.469   515   599 W InputReader: Device virtio_input_multi_touch_7 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.469   515   599 W InputReader: Device virtio_input_multi_touch_5 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.469   515   599 W InputReader: Device virtio_input_multi_touch_2 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.469   515   599 W InputReader: Device virtio_input_multi_touch_6 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.469   515   599 W InputReader: Device virtio_input_multi_touch_3 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.469   515   599 W InputReader: Device virtio_input_multi_touch_8 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.492  9265  9265 I _james_park_ap: The ClassLoaderContext is a special shared library.
08-27 21:41:07.509  9265  9265 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-27 21:41:07.511  9265  9265 D NetworkSecurityConfig: No Network Security Config specified, using platform default
08-27 21:41:07.528  9265  9265 I FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
08-27 21:41:07.532  9265  9265 I FirebaseInitProvider: FirebaseApp initialization successful
08-27 21:41:07.570   515   599 D CompatibilityChangeReporter: Compat change id reported: 136274596; UID 10164; state: ENABLED
08-27 21:41:07.599  9265  9297 D libEGL  : loaded /vendor/lib/egl/libEGL_emulation.so
08-27 21:41:07.603  9265  9297 D libEGL  : loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
08-27 21:41:07.613  9265  9297 D libEGL  : loaded /vendor/lib/egl/libGLESv2_emulation.so
08-27 21:41:07.620  9265  9265 E FlutterLoader: Flutter initialization failed.
08-27 21:41:07.620  9265  9265 E FlutterLoader: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at java.util.concurrent.FutureTask.report(FutureTask.java:123)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at java.util.concurrent.FutureTask.get(FutureTask.java:193)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at h6.d.e(Unknown Source:28)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at io.flutter.embedding.engine.d.<init>(Unknown Source:35)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at io.flutter.embedding.android.e.G(Unknown Source:172)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at io.flutter.embedding.android.e.p(Unknown Source:7)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at io.flutter.embedding.android.d.onCreate(Unknown Source:13)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at android.app.Activity.performCreate(Activity.java:8000)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at android.app.Activity.performCreate(Activity.java:7984)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at android.os.Handler.dispatchMessage(Handler.java:106)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at android.os.Looper.loop(Looper.java:223)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at android.app.ActivityThread.main(ActivityThread.java:7656)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at java.lang.reflect.Method.invoke(Native Method)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
08-27 21:41:07.620  9265  9265 E FlutterLoader: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at java.lang.System.loadLibrary(System.java:1664)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at io.flutter.embedding.engine.FlutterJNI.loadLibrary(Unknown Source:13)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at h6.d$a.b(Unknown Source:18)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at h6.d$a.call(Unknown Source:0)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-27 21:41:07.620  9265  9265 E FlutterLoader:         at java.lang.Thread.run(Thread.java:923)
08-27 21:41:07.621  9265  9265 D AndroidRuntime: Shutting down VM
08-27 21:41:07.623  9265  9265 E AndroidRuntime: FATAL EXCEPTION: main
08-27 21:41:07.623  9265  9265 E AndroidRuntime: Process: com.gmail.joelc0193.st_james_park_app, PID: 9265
08-27 21:41:07.623  9265  9265 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gmail.joelc0193.st_james_park_app/com.gmail.joelc0193.st_james_park_app.MainActivity}: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7656)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
08-27 21:41:07.623  9265  9265 E AndroidRuntime: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at h6.d.e(Unknown Source:438)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at io.flutter.embedding.engine.d.<init>(Unknown Source:35)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at io.flutter.embedding.android.e.G(Unknown Source:172)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at io.flutter.embedding.android.e.p(Unknown Source:7)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at io.flutter.embedding.android.d.onCreate(Unknown Source:13)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8000)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7984)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        ... 11 more
08-27 21:41:07.623  9265  9265 E AndroidRuntime: Caused by: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at h6.d.e(Unknown Source:28)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        ... 19 more
08-27 21:41:07.623  9265  9265 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1664)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at io.flutter.embedding.engine.FlutterJNI.loadLibrary(Unknown Source:13)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at h6.d$a.b(Unknown Source:18)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at h6.d$a.call(Unknown Source:0)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-27 21:41:07.623  9265  9265 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
08-27 21:41:07.633   515   599 W ActivityTaskManager:   Force finishing activity com.gmail.joelc0193.st_james_park_app/.MainActivity
08-27 21:41:07.634   515  9299 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
08-27 21:41:07.637   306   351 D goldfish-address-space: claimShared: Ask to claim region [0x3f4ab0000 0x3f5560000]
08-27 21:41:07.649   515   542 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
08-27 21:41:07.649   515   542 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
08-27 21:41:07.681  9265  9265 I Process : Sending signal. PID: 9265 SIG: 9
08-27 21:41:07.712   515   536 D EventSequenceValidator: dec AccIntentStartedEvents to 1
08-27 21:41:07.783   986  1004 I s.nexuslaunche: NativeAlloc concurrent copying GC freed 9000(522KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 4076KB/8152KB, paused 881us total 125.841ms
08-27 21:41:07.798   515  3987 I ActivityManager: Process com.gmail.joelc0193.st_james_park_app (pid 9265) has died: fg  TOP 
08-27 21:41:07.805   290   290 I Zygote  : Process 9265 exited due to signal 9 (Killed)
08-27 21:41:07.815   515  3987 W InputReader: Device virtio_input_multi_touch_10 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.815   515  3987 W InputReader: Device virtio_input_multi_touch_4 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.815   515  3987 W InputReader: Device virtio_input_multi_touch_11 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.815   515  3987 W InputReader: Device virtio_input_multi_touch_9 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.816   515  3987 W InputReader: Device virtio_input_multi_touch_7 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.816   515  3987 W InputReader: Device virtio_input_multi_touch_5 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.816   515  3987 W InputReader: Device virtio_input_multi_touch_2 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.816   515  3987 W InputReader: Device virtio_input_multi_touch_6 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.816   515  3987 W InputReader: Device virtio_input_multi_touch_3 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.816   515  3987 W InputReader: Device virtio_input_multi_touch_8 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.816   515  3987 W InputReader: Device virtio_input_multi_touch_10 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.816   515  3987 W InputReader: Device virtio_input_multi_touch_4 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.816   515  3987 W InputReader: Device virtio_input_multi_touch_11 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.816   515  3987 W InputReader: Device virtio_input_multi_touch_9 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.816   515  3987 W InputReader: Device virtio_input_multi_touch_7 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.816   515  3987 W InputReader: Device virtio_input_multi_touch_5 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.816   515  3987 W InputReader: Device virtio_input_multi_touch_2 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.817   515  3987 W InputReader: Device virtio_input_multi_touch_6 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.817   515  3987 W InputReader: Device virtio_input_multi_touch_3 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.817   515  3987 W InputReader: Device virtio_input_multi_touch_8 is associated with display ADISPLAY_ID_NONE.
08-27 21:41:07.848   515   544 I libprocessgroup: Successfully killed process cgroup uid 10164 pid 9265 in 47ms
08-27 21:41:07.889   515   947 W ActivityManager: Unable to start service Intent { act=android.service.appprediction.AppPredictionService cmp=com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiPredictionService } U=0: not found
08-27 21:41:07.894   515   947 W RemoteAppPredictionService: could not bind to Intent { act=android.service.appprediction.AppPredictionService cmp=com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiPredictionService } using flags 67108865
08-27 21:41:07.960   366   366 E Layer   : [Surface(name=Task=341)/@0xcd76f81 - animation-leash#0] No local sync point found
08-27 21:41:07.960   366   366 E Layer   : [Surface(name=Task=1)/@0xb2bdf58 - animation-leash#0] No local sync point found
08-27 21:41:07.990   515  4999 D HostConnection: HostConnection::get() New Host Connection established 0xb8fd8ea0, tid 4999
08-27 21:41:08.017   515  4999 D HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_YUV_Cache ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
08-27 21:41:08.018   515  4999 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
08-27 21:41:08.019   515  4999 D EGL_emulation: eglCreateContext: 0xb9042a80: maj 3 min 0 rcv 3
08-27 21:41:08.024   515  4999 D EGL_emulation: eglMakeCurrent: 0xb9042a80: ver 3 0 (tinfo 0xaac36830) (first time)
08-27 21:41:08.136   515   536 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{eea4302 u0 com.gmail.joelc0193.st_james_park_app/.MainActivity t-1 f}}
08-27 21:41:10.381   515  3987 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
08-27 21:41:12.234   406   406 I perfetto: probes_producer.cc:329  Producer stop (id=49)
08-27 21:41:12.237   406   406 I perfetto: ftrace_procfs.cc:183    disabled ftrace
08-27 21:41:12.237   415   415 I perfetto: ng_service_impl.cc:1948 Tracing session 49 ended, total sessions:0
08-27 21:41:12.221     0     0 W perfetto: disabled ftrace
08-27 21:41:12.927  1116  1197 I PeriodicStatsRunner: PeriodicStatsRunner.call():180 call()
08-27 21:41:12.927  1116  1197 I PeriodicStatsRunner: PeriodicStatsRunner.call():184 No submit PeriodicStats since input started.
08-27 21:41:15.727   490   490 E netmgr  : qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:network' service: Invalid argument
08-27 21:41:15.728   490   490 E netmgr  : Failed to open QEMU pipe 'qemud:network': Invalid argument
08-27 21:41:15.993   497   497 E wifi_forwarder: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:wififorward' service: Invalid argument
08-27 21:41:15.993   497   497 E wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe
08-27 21:42:15.747   490   490 E netmgr  : qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:network' service: Invalid argument
08-27 21:42:15.748   490   490 E netmgr  : Failed to open QEMU pipe 'qemud:network': Invalid argument
08-27 21:42:16.044   497   497 E wifi_forwarder: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:wififorward' service: Invalid argument
08-27 21:42:16.044   497   497 E wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe

**Comment by eseidel** [comment]
OK:
```08-27 21:41:07.620 9265 9265 E FlutterLoader: Flutter initialization failed.
08-27 21:41:07.620 9265 9265 E FlutterLoader: java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
```

And:
```
08-27 21:41:07.434 9265 9265 W _james_park_ap: Unexpected CPU variant for X86 using defaults: x86
```

I presume this is running in an x86 emulator or x86 device?

We just realized on Friday we had failed to publish the x86 assets for the last few builds.  Which I suspect is the issue here.  Preview should probably have been smart enough not to install a non-x86 apk on an x86 device though.

We should have an x86 fix in the next few days.

**Comment by joelc0193** [comment]
yes this is running on an x86 emulator.

so the answer is to wait then. Thanks!

**Comment by eseidel** [comment]
Yeah. Sorry, we discovered on Friday that we hadn't been producing x86 builds of the shorebird engine for a while, but now that we've discovered it the fix should be easy.   I expect our next release of shorebird (in the next couple days) will include x86 support.

**Comment by eseidel** [comment]
Just wanted to let you know we have not forgotten.  Just been a busy week with some other infrastructure changes and we haven't gotten to this yet.

**Comment by eseidel** [comment]
OK, so we looked at this (and even tried to set up our builders to produce Shorebird binaries for x86 Android). We cannot produce an x86 Android binary at this time.  Why?
- Shorebird is a release-only product (Shorebird doesn't make a lot of sense in "debug" builds since debug builds have hot reload already)
- Flutter release mode uses Dart AOT mode
- Dart AOT mode does not support x86: https://github.com/dart-lang/sdk/wiki/Supported-Architectures

We could make a Shorebird engine with Dart JIT mode and Flutter release.  But I suspect the correct solution is for our tool to detect this case (that it's being asked to run on an x86 emulator), refuse to and show a nice error message about using an ARM emulator instead.

Have you tried using an ARM emulator?  Let us know if that's not an option for you.
https://stackoverflow.com/questions/30405740/android-studio-how-can-i-make-an-avd-with-arm-instead-of-haxm

**Comment by eseidel** [comment]
@bryanoltman so I think the fix here is in `shorebird` to have it detect the arch of the device it's about to connect to and if it's x86 to show and error and maybe point to the above comment:
https://stackoverflow.com/questions/6630386/how-to-find-arm-processor-version-on-android-device

**Comment by joelc0193** [comment]
I can use an ARM emulator, thank you!

**Comment by eseidel** [comment]
This is very related to https://github.com/shorebirdtech/shorebird/issues/1432, which is about missing iOS simulator support.  This is about missing x86 Android support, and that we could better log about either of those cases.
