### ISSUE TITLE
fix: shorebird CLI do not work "--device-id" option of preview command.

### ISSUE THREAD

**Issue by cafefarm-johnny** [shorebirdtech/shorebird#1186]
**Description**

it will not work passed `--device-id` option with preview command.

**Steps To Reproduce**

1. Execute `shorebird preview --device-id <emulator device id>`
2. exception with message. "Exception: Failed to install apks: [BT:1.14.1] Error: More than one device connected, please provide --device-id."

**Expected Behavior**

I'm running two emulator (or real device) and i tried preview command with `--device-id` option target one emulator.
I expected run app but i caught exception message and failed run app.

**Additional Context**

```bash
$ adb devices
List of devices attached
emulator-5554   device
emulator-5556   device

$ shorebird preview --device-id emulator-5554
✓ Fetching apps (0.5s)
Which app would you like to preview? flutter_mask (dev)
✓ Fetching releases (0.3s)
Which release would you like to preview? 1.0.1+2
Which platform would you like to preview? android
✓ Extracting metadata (0.5s)
⠴ Installing apks... (0.4s)
✗ Exception: Failed to install apks: [BT:1.14.1] Error: More than one device connected, please provide --device-id.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: More than one device connected, please provide --device-id.
        at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
        at com.android.tools.build.bundletool.device.DeviceAnalyzer.getTargetDevice(DeviceAnalyzer.java:170)
        at com.android.tools.build.bundletool.device.DeviceAnalyzer.getAndValidateDevice(DeviceAnalyzer.java:133)
        at com.android.tools.build.bundletool.device.DeviceAnalyzer.getDeviceSpec(DeviceAnalyzer.java:55)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:193)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:117)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:55)
 (1.5s)
```

**Comment by cafefarm-johnny** [comment]
It is do not occur if running only one device on OS,

**Comment by eseidel** [comment]
It looks like we're not passing the --device-id flag on to bundletool.

It accepts --device-id:
https://developer.android.com/tools/bundletool

But I don't see us forwarding it:
https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/bundletool.dart#L54

Should be an easy fix.  Thank you for reporting!
