### ISSUE TITLE
`shorebird preview` crashes when a release is empty

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1208]
Reported on discord:
```
hi everyone, im having trouble after upgrade shorebird and my apps in vscode keep on "Running Gradle task 'assembleDebug'." not sure what is happening here and im unable to shorebird preview as it says
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      Logger.chooseOne (package:mason_logger/src/mason_logger.dart:353:65)
#2      PreviewCommand.promptForPlatform (package:shorebird_cli/src/commands/preview_command.dart:122:29)
#3      PreviewCommand.run (package:shorebird_cli/src/commands/preview_command.dart:90:47)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#5      ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/command_runner.dart:167:18)
<asynchronous suspension>
#6      ShorebirdCliCommandRunner.run (package:shorebird_cli/src/command_runner.dart:95:14)
<asynchronous suspension>
#7      main (file:///Users/macbookpro/.shorebird/packages/shorebird_cli/bin/shorebird.dart:29:5)
<asynchronous suspension>.
```

**Comment by eseidel** [comment]
Looks like we guide most of the rest of our "chooseOne" calls, but not this one:
https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/commands/preview_command.dart#L132

**Comment by bryanoltman** [comment]
Looking at the preview command code, it appears as though this is fixed.
