### ISSUE TITLE
feat: no connected devices message

### ISSUE THREAD

**Issue by LeonardoRosaa** [shorebirdtech/shorebird#1320]
**Description**

Should the Shorebird project keep this exception message when the user doesn't have any device connected?

```
Which platform would you like to preview? android
✓ Extracting metadata (0.3s)
✗ Exception: Failed to install apks: [BT:1.14.1] Error: No connected devices found.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: No connected devices found.
	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getTargetDevice(DeviceAnalyzer.java:160)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getAndValidateDevice(DeviceAnalyzer.java:133)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getDeviceSpec(DeviceAnalyzer.java:55)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:193)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:117)
```

Perhaps, a one-line message should be good enough and clearer for the user. For example:

```
Which platform would you like to preview? android
✓ Extracting metadata (0.3s)
✗ No connected devices found
```

**Comment by eseidel** [comment]
Thank you for filing!

The error looks correct.  It would be nice to show something shorter.  But I don't think we're going to get to this for quiet a while.
