### ISSUE TITLE
`shorebird preview` fails on Windows

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1369]
**Description**

On the current `main` branch, `shorebird preview` is failing on Windows with the following output:

```
✓ Fetching releases (76ms)
Which release would you like to preview?
Which release would you like to preview? 1.0.0+1
Which platform would you like to preview?
Which platform would you like to preview? android
[HTTP] GET https://api.shorebird.dev/api/v1/apps/54718912-10f7-4432-9513-b387996a662e/releases/11699/artifacts?arch=aab&platform=android
✓ Fetching aab artifact (73ms)
[HTTP] GET https://storage.googleapis.com/shorebird_release_artifacts/54718912-10f7-4432-9513-b387996a662e/android/aab/11699/dlc.vmcode
✓ Downloading release (3.1s)
✓ Using production track (15.9s)
⠦ Extracting metadata... (4.5s)[Process.run] C:\Program Files\Android\Android Studio\jbr\bin\java.exe -jar C:\Users\bryan\Documents\shorebirdtech\_shorebird\shorebird\bin\cache\artifacts\bundletool\bundletool.jar dump manifest --bundle=C:\Users\bryan\Documents\shorebirdtech\_shorebird\shorebird\bin\cache\previews\54718912-10f7-4432-9513-b387996a662e\android_1.0.0+1.aab --xpath /manifest/@package
✗ Exception: Failed to extract package name from app bundle: [BT:1.14.1] Error: File 'base/manifest/AndroidManifest.xml' not found.
com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: File 'base/manifest/AndroidManifest.xml' not found.
        at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
        at com.android.tools.build.bundletool.commands.DumpManager.extractAndParse(DumpManager.java:198)
        at com.android.tools.build.bundletool.commands.DumpManager.extractAndParse(DumpManager.java:181)
        at com.android.tools.build.bundletool.commands.DumpManager.printManifest(DumpManager.java:78)
        at com.android.tools.build.bundletool.commands.DumpCommand.execute(DumpCommand.java:153)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:129)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:55)
 (5.0s)
```

**Steps To Reproduce**

1. Create a new Flutter app
2. Init shorebird
3. Create an Android release
4. `shorebird preview` that release

**Comment by bryanoltman** [comment]
Details:

- This is in Powershell 5.1
- Subsequent runs of `shorebird preview` fail with the error "Unable to find shorebird.yaml"

**Comment by bryanoltman** [comment]
I attempted to unzip `C:\Users\bryan\Documents\shorebirdtech\_shorebird\shorebird\bin\cache\previews\54718912-10f7-4432-9513-b387996a662e\android_1.0.0+1.aab`, but it was empty after unzipping 🤔

**Comment by bryanoltman** [comment]
(the aab file is 24MB on disk, so it's possible I did something wrong when unzipping)

**Comment by bryanoltman** [comment]
It extracts to a non-empty directory on my mac, so this is probably just me being a clumsy windows user

**Comment by bryanoltman** [comment]
Hrm, opening the aab in Android Studio shows all the files to be there

![image](https://github.com/shorebirdtech/shorebird/assets/581764/582b9bac-d70a-4c79-bfc8-185ba0b71ccf)

**Comment by bryanoltman** [comment]
Looks like our problem lies with bundletool:

```
$ java.exe -jar C:\Users\bryan\Documents\shorebirdtech\_shorebird\shorebird\bin\cache\artifacts\bundletool\bundletool.jar dump manifest --bundle=C:\Users\bryan\Documents\shorebirdtech\_shorebird\shorebird\bin\cache\previews\54718912-10f7-4432-9513-b387996a662e\android_1.0.0+1.aab
[BT:1.14.1] Error: File 'base/manifest/AndroidManifest.xml' not found.
com.android.tools.build.bundletool.model.exceptions.InvalidBundleException: File 'base/manifest/AndroidManifest.xml' not found.
        at com.android.tools.build.bundletool.model.exceptions.UserExceptionBuilder.build(UserExceptionBuilder.java:58)
        at com.android.tools.build.bundletool.commands.DumpManager.extractAndParse(DumpManager.java:198)
        at com.android.tools.build.bundletool.commands.DumpManager.extractAndParse(DumpManager.java:181)
        at com.android.tools.build.bundletool.commands.DumpManager.printManifest(DumpManager.java:78)
        at com.android.tools.build.bundletool.commands.DumpCommand.execute(DumpCommand.java:153)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:129)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:55)
```

Java is:

```
$ where.exe java.exe
C:\Program Files\Android\Android Studio\jbr\bin\java.exe
```

**Comment by bryanoltman** [comment]
I'm able to preview this release on a Mac
