### ISSUE TITLE
fix: failing test `dartkp-dart_precompiled release_arm64 corelib/unicode_test`

### ISSUE THREAD

**Issue by kmillikin** [shorebirdtech/shorebird#1458]
This test fails with a runtime error in the precompiled runtime.  It's kind of a weird one:

```
stderr:
Unhandled exception:
Expect.equals(expected: <STRASSE>, actual: <STRA\xDFE>) fails.
#0      Expect._fail (package:expect/expect.dart:696)
#1      Expect.equals (package:expect/expect.dart:117)
#2      UnicodeTest.testMain (file:///Users/kmillikin/dart-sdk/sdk/tests/corelib/unicode_test.dart:10)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296)
#4      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)

--- Re-run this test:
python3 tools/test.py -m release -c dartkp -r dart_precompiled -a arm64 corelib/unicode_test
```

**Comment by kmillikin** [comment]
We are also failing `dartkp-dart_precompiled release_arm64 corelib/string_case_test/01` with probably the same issue:

```
Unhandled exception:
Expect.equals(expected: <SS>, actual: <\xDF>) fails.
#0      Expect._fail (package:expect/expect.dart:696)
#1      Expect.equals (package:expect/expect.dart:117)
#2      testSpecialCases (file:///Users/kmillikin/dart-sdk/sdk/xcodebuild/ReleaseARM64/generated_tests/corelib/string_case_test_01.dart:24)
#3      main (file:///Users/kmillikin/dart-sdk/sdk/xcodebuild/ReleaseARM64/generated_tests/corelib/string_case_test_01.dart:9)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)

--- Re-run this test:
python3 tools/test.py -m release -c dartkp -r dart_precompiled -a arm64 corelib/string_case_test/01
```

**Comment by kmillikin** [comment]
These both fail upstream.
