### ISSUE TITLE
fix: failing test `dartkp-dart_precompiled release_arm64 corelib/bool_from_environment_test`

### ISSUE THREAD

**Issue by kmillikin** [shorebirdtech/shorebird#1460]
This fails at runtime, it looks a little weird.  Verify that we are actually expected to pass this in the given configuration.

```
Unhandled exception:
FormatException: Must specify at least one of compiler or runtime in options or configuration name.
#0      Configuration.parse (package:smith/configuration.dart:239)
#1      _configuration (package:expect/config.dart:18)
#2      isVmJitConfiguration (package:expect/config.dart)
#3      isVmConfiguration (package:expect/config.dart:34)
#4      main (file:///Users/kmillikin/dart-sdk/sdk/tests/corelib/bool_from_environment_test.dart:15)
#5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)

--- Re-run this test:
python3 tools/test.py -m release -c dartkp -r dart_precompiled -a arm64 corelib/bool_from_environment_test
```

**Comment by kmillikin** [comment]
This fails upstream.
