### ISSUE TITLE
Preview can target iOS on Windows

### ISSUE THREAD

**Issue by atadeuccislideworks** [shorebirdtech/shorebird#1561]
**Description**

When using `shorebird preview`, after selection which version to preview, the cli stops running after "Locating device for run" without saying why it stopped.

**Steps To Reproduce**

1. Run `shorebird preview`
2. Select the version
3. Nothing happens after "Locating device for run"

**Expected Behavior**

Expected the CLI to tell me why it didn't open the app.

**Screenshots**

![image](https://github.com/shorebirdtech/shorebird/assets/108531792/5b31ec77-c3f2-4b23-8aa9-a161db76dcbc)

**Additional Context**

```
shorebird --version
Shorebird 0.18.5 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.13.9 • revision a3d5f7c614aa1cc4d6cb1506e74fd1c81678e68e
Engine • revision 0757a9001dc3dcfce6f09fdd443904827274d22e
```

**Comment by atadeuccislideworks** [comment]
While creating this issue I tried using the verbose option in the CLI and found the issue, it's trying to install iOS version to android (or windows? idk).

Error was: `Error launching app. ProcessException: %1 is not a valid Win32 application.`

Output of `flutter preview --verbose`

```
shorebird preview --verbose
[HTTP] GET https://api.shorebird.dev/api/v1/apps/a589fbfd-c742-4b51-8f74-1026f53f06b5/releases?sideloadable=true
✓ Fetching releases (0.4s)
Which release would you like to preview?
  ◯  1.0.3+13
❯ ◉  1.0.2+12
  ◯  1.0.1+11
  ◯  1.0.0+10
  ◯  1.0.0+9
  ◯  1.0.0+8
  ◯  1.0.0+7
  ◯  1.0.0+6
  ◯  1.0.0+5
  ◯  1.0.0+4
  ◯  1.0.0+3
  ◯  1.0.0+2
Which release would you like to preview? 1.0.2+12
✓ Using production track (14ms)
[Process.run] xcrun devicectl --version
✓ Locating device for run (8ms)
Using ios-deploy to install and launch.
[Process.run] C:\Users\slide\.shorebird\bin\cache\flutter\a3d5f7c614aa1cc4d6cb1506e74fd1c81678e68e\bin\flutter precache --ios --verbose
Error launching app. ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\slide\.shorebird\bin\cache\flutter\a3d5f7c614aa1cc4d6cb1506e74fd1c81678e68e\bin\flutter precache --ios --verbose #0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:578:18)
#3      Process.run (dart:io-patch/process_patch.dart:49:12)
#4      ProcessWrapper.run (package:shorebird_cli/src/process.dart:270:34)
#5      ShorebirdProcess.run (package:shorebird_cli/src/process.dart:74:41)
#6      IOSDeploy.installIfNeeded (package:shorebird_cli/src/executables/ios_deploy.dart:305:34)
#7      IOSDeploy.installAndLaunchApp (package:shorebird_cli/src/executables/ios_deploy.dart:140:11)
#8      PreviewCommand.installAndLaunchIos (package:shorebird_cli/src/commands/preview_command.dart:384:43)
<asynchronous suspension>
#9      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#10     ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/command_runner.dart:177:18)
<asynchronous suspension>
#11     ShorebirdCliCommandRunner.run (package:shorebird_cli/src/command_runner.dart:93:14)
<asynchronous suspension>
#12     main (file:///C:/Users/slide/.shorebird/packages/shorebird_cli/bin/shorebird.dart:27:5)
<asynchronous suspension>
```

Here's the patches of the current release:

![image](https://github.com/shorebirdtech/shorebird/assets/108531792/63b47572-3d28-496a-a318-df92fe40b71b)

**Comment by bryanoltman** [comment]
It definitely looks like this is trying to run the iOS version of your app, which it definitely shouldn't be doing on Windows. We'll look into it, thanks for the report!

**Comment by bryanoltman** [comment]
Created https://github.com/shorebirdtech/shorebird/pull/1585 to fix this. Until this fix is landed and released, you can provide the `--platform android` argument to `shorebird preview` to make previews work.
