### ISSUE TITLE
fix: Encountered error while archiving for device

### ISSUE THREAD

**Issue by Dario-Maselli** [shorebirdtech/shorebird#1739]
App ID: 6989e316-6c49-4d27-bc1f-b0c56d92f17e

**Description**

After setting up a Codemagic.yaml workflow, we run into this error: ```Encountered error while archiving for device.```. 

**Steps To Reproduce**

1. Create codemagic.yaml workflow (like below)
2. Upload IOS signing certificates + provisioning profiles
3. Run the workflow
4. Result: Encountered error

Gives this error:
```
[   +1 ms] Encountered error while archiving for device.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:665:7)
           <asynchronous suspension>
           #2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:417:50)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1336:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:296:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:244:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:91:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>


 (156.8s)
```

**Expected Behavior**
```Running shorebird release ios --target ./lib/main_staging.dart --flavor staging --flutter-version 3.10.6 --no-codesign -v``` works on the macbook (without the ```--no-codesign```) and can successfully upload to your Shorebird servers, but running through the codemagic workflow fails...

**Screenshots**

If applicable, add screenshots to help explain your
![CodeMagic](https://github.com/shorebirdtech/shorebird/assets/117168592/71a48ee6-7232-4f7e-8150-1e2c21e39861)
 problem.

**Additional Context**

For additional context, here is the workflow file:
```workflows:
  build-app:
    name: Build App with Shorebird
    cache:
      cache_paths:
        - ~/.pub-cache
        - Pods/
        - Podfile.lock
    environment:
      vars:
        TYPE: "patch" 
      groups:
        - shorebird

      flutter: 3.10.6
      xcode: 14.3.1
      cocoapods: 1.15.2

      ios_signing:
        distribution_type: app_store
        bundle_identifier: <our app bundle (not sure if this is a security risk so I removed it)>

    instance_type: mac_mini_m1
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - subfolder_name/build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - build/macos/**/*.pkg
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      - /Users/builder/.pub-cache/log/pub_log.txt.gz

    scripts:
      - name: 🔑 Create key.properties file for Android
<I have removed this for privacy reasons>

      - name: 📦 Setup ENV and Firebase Configs
<I have removed this for privacy reasons>

      - name: 🐧Run Flutter Pub Get
        script: flutter pub get

      - name: ☕ Install CocoaPods
        script: |
          (cd ./ios && pod install --repo-update)

      - name: 🐦 Setup Shorebird
        script: |
          # Install Shorebird
          curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash

          # Add Shorebird to PATH
          echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV

      - name: 🖊 Set up code signing settings on Xcode project
        script: xcode-project use-profiles

      - name: 🙌 Shorebird Build
        script: |
          echo "➡️ Using type: $TYPE"

          # If type is neither "patch" nor "release", exit with error
          if [ "$TYPE" != "patch" ] && [ "$TYPE" != "release" ]; then
            echo "TYPE must be either 'patch' or 'release'"
            exit 1
          fi

          # Check type and run corresponding command
          if [ "$TYPE" == "patch" ]; then
            echo "🩹 Running patch command"
            shorebird patch ios --target ./lib/main_staging.dart --flavor staging --flutter-version 3.10.6 --no-codesign -v
            shorebird patch android --target ./lib/main_staging.dart --flavor staging --flutter-version 3.10.6 --no-codesign -v
          elif [ "$TYPE" == "release" ]; then
            echo "🚀 Running release command"
            shorebird release ios --target ./lib/main_staging.dart --flavor staging --flutter-version 3.10.6 --no-codesign -v
            # shorebird release android --target ./lib/main_staging.dart --flavor staging --flutter-version 3.10.6 --no-codesign -v
          fi

```

**Comment by Dario-Maselli** [comment]
If you need more information and a better verbose output, I am happy to assist. 🙏🏻 Codemagic freezes if I try to load too much logs onto the screen. I am trying to find a way to get the full verbose output without the ```IO  : Writing 354418 characters to text file /Users/builder/.pub-cache/log/pub_log.txt.``` content being dumped to the logs as well.

**Comment by Dario-Maselli** [comment]
Ran into this locally now:
```
✗ Failed to build: Swift Compiler Error (Xcode): Compiling for iOS 12, but module 'workmanager' has a minimum deployment target of iOS 16.0: /Users/sinov8/Library/Developer/Xcode/DerivedData/Runner-dxfvpghvhuboceelchnbodukehin/Build/Intermediates.noindex/ArchiveIntermediates/staging/BuildProductsPath/Release-staging-iphoneos/workmanager/workmanager.framework/Modules/workmanager.swiftmodule/arm64-apple-ios.swiftmodule
/Users/sinov8/StudioProjects/redrabbit_flutter_app/ios/Runner/AppDelegate.swift:2:7

Encountered error while archiving for device.
 (97.0s)
```
 
 This time, it told me exactly what was throwing the error, I fixed it locally but still able to reproduce it on CodeMagic sadly...

**Comment by bryanoltman** [comment]
> If you need more information and a better verbose output, I am happy to assist

Yes, verbose logs would be very helpful here if you could provide them

**Comment by Dario-Maselli** [comment]
Here you go, I couldn't get my pastebin to work (I think this file is too big), apologies for the text file.

[Build Logs.txt](https://github.com/shorebirdtech/shorebird/files/14347898/Build.Logs.txt)

**Comment by Dario-Maselli** [comment]
I think it may have to do with the cocoa pods and where they are generating (this is just a wild guess).

**Comment by bryanoltman** [comment]
I'm seeing this in the output:

```
               ♦ /Users/builder/.shorebird/bin/cache/flutter/03e895ee09dfbb9c18681d103f4b27671ff65429/bin/flutter --verbose assemble --no-version-check --output=/Users/builder/Library/Developer/Xcode/DerivedData/Runner-edaimyiflreloheqntgnhkmwcclv/Build/Intermediates.noindex/ArchiveIntermediates/staging/BuildProductsPath/Release-staging-iphoneos/ -dTargetPlatform=ios -dTargetFile=lib/main_staging.dart -dBuildMode=release -dIosArchs=arm64 -dSdkRoot=/Applications/Xcode-14.3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk -dSplitDebugInfo= -dTreeShakeIcons=true -dTrackWidgetCreation=false -dDartObfuscation=false -dAction=install --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions= -dCodesignIdentity=A52C780FB61C0E88C2CC3832472AAC700DB58F6D release_ios_bundle_flutter_assets

.... // omitted for brevity

               staging
               Looking for GoogleService-Info.plist in /Users/builder/clone/ios/Config/staging/GoogleService-Info.plist
               No GoogleService-Info.plist found. Please ensure it's in the proper directory.
               Command PhaseScriptExecution failed with a nonzero exit code
```

It looks like your GoogleService-Info.plist might not be present in the CI environment?

**Comment by Dario-Maselli** [comment]
Aah! That's it! Thank you so much! Apologies that it was not shorebird related. I really appreciate the support. Closing as completed. 🙏🏻🎉 You are a legend.

**Comment by bryanoltman** [comment]
No problem! Glad we could help 🙂
