### ISSUE TITLE
fix: local engine builds broken

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#2103]
**Description**

Seems we broke using a local engine in the CLI refactor

**Steps To Reproduce**

`shorebird release android --local-engine-src-path=shorebirdtech/engine/src --local-engine android_release --local-engine-host=host_release -v`

```
Bad state: No element
#0      ListBase.firstWhere (dart:collection/list.dart:132:5)
#1      AndroidReleaser.buildReleaseArtifacts.<anonymous closure> (package:shorebird_cli/src/commands/release/android_releaser.dart:83:16)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#3      ListIterable.toSet (dart:_internal/iterable.dart:229:18)
#4      AndroidReleaser.buildReleaseArtifacts (package:shorebird_cli/src/commands/release/android_releaser.dart:85:10)
#5      ReleaseCommand.createRelease.<anonymous closure> (package:shorebird_cli/src/commands/release/release_command.dart:215:48)
<asynchronous suspension>
#6      ReleaseCommand.createRelease (package:shorebird_cli/src/commands/release/release_command.dart:211:12)
<asynchronous suspension>
#7      ReleaseCommand.run (package:shorebird_cli/src/commands/release/release_command.dart:135:7)
<asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#9      ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/command_runner.dart:209:20)
<asynchronous suspension>
#10     ShorebirdCliCommandRunner.run (package:shorebird_cli/src/command_runner.dart:124:14)
<asynchronous suspension>
#11     main (file:///Users/felix/Development/github.com/shorebirdtech/_shorebird/shorebird/packages/shorebird_cli/bin/shorebird.dart:32:5)
<asynchronous suspension>
```

**Comment by bryanoltman** [comment]
This is because you're missing the `--target-platform` option. In this case, I think you want to pass `--target-platform=android-arm64`

**Comment by bryanoltman** [comment]
With this, however, I'm seeing a different failure:

```
✗ Failed to build: Unhandled exception:
Crash when compiling package:ms_test/main.dart:
Unexpected Kernel SDK Version 037420eec9 (expected a210745c4f).

#0      BinaryBuilder._readAndVerifySdkHash (package:kernel/binary/ast_from_binary.dart:657)
#1      BinaryBuilder._verifyComponentInitialBytes (package:kernel/binary/ast_from_binary.dart:874)
#2      BinaryBuilder.readComponent.<anonymous closure> (package:kernel/binary/ast_from_binary.dart:697)
#3      Timeline.timeSync (dart:developer/timeline.dart:173)
#4      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:695)
#5      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:479)
#6      ProcessedOptions.loadSdkSummary (package:front_end/src/base/processed_options.dart:426)
<asynchronous suspension>
#7      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:83)
<asynchronous suspension>
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#9      kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:65)
<asynchronous suspension>
#10     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:139)
<asynchronous suspension>
#11     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:64)
<asynchronous suspension>
#12     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:50)
<asynchronous suspension>
#13     compileToKernel (package:vm/kernel_front_end.dart:469)
<asynchronous suspension>
#14     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:639)
<asynchronous suspension>
#15     starter (package:frontend_server/starter.dart:101)
<asynchronous suspension>
#16     main (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
<asynchronous suspension>

Target kernel_snapshot failed: Exception
```

**Comment by bryanoltman** [comment]
I believe this should be fixed by https://github.com/shorebirdtech/dart-sdk/pull/468
