### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by temuujinnn** [shorebirdtech/shorebird#2115]
✗ Exception: Failed to install apks: [BT:1.15.6] Error: No connected devices found.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: No connected devices found.
        at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
        at com.android.tools.build.bundletool.device.DeviceAnalyzer.getTargetDevice(DeviceAnalyzer.java:160)
        at com.android.tools.build.bundletool.device.DeviceAnalyzer.getAndValidateDevice(DeviceAnalyzer.java:133)
        at com.android.tools.build.bundletool.device.DeviceAnalyzer.getDeviceSpec(DeviceAnalyzer.java:55)
        at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:202)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:117)
        at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:55)
 (0.2s)

If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also file an issue if you think this is a bug. Please include the following log file in your report:
/Users/garage/Library/Application Support/shorebird/logs/1715848389322_shorebird.log

**Comment by eseidel** [comment]
This looks like a log from `shorebird preview`?  Where its calling `bundletool install-apks` and there isn't a device to install onto?

**Comment by bryanoltman** [comment]
"No connected devices found" is the issue – there are no devices that this app can be installed to. If you either start an emulator or connect a device, this will go away.
