### ISSUE TITLE
`shorebird preview` not targeting iOS device for release with both Android and iOS builds

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#2153]
App ID: `0f7a6dc6-bccc-4343-a208-3a63a9cb8b3f`
Release `1.2.44+1244` (id 57524)

**Description**

A release was created for both iOS and Android. Attempting to run `shorebird preview` with only an iOS device available (no Android emulator or device) is attempting to run the Android version of the app, even when an iOS device ID is specified. The user is not seeing the multi-choice platform prompt.

Sample log output:

```
$ shorebird preview ios --device-id 00008130-[redacted]
Which app flavor?
❯ ◉  prod
  ◯  beta
Which app flavor? prod
⠸ Fetching releases... (0.2s)
✓ Fetching releases (0.5s)
Which release would you like to preview?
❯ ◉  1.2.44+1244
Which release would you like to preview? 1.2.44+1244
✓ Using production track (0.9s)
✓ Extracting metadata (0.2s)
⠹ Building apks... (1.8s)^C
```

**Solution (waiting for confirmation)**: The issue seems to be that the iOS release artifact was generated with the `--no-codesign` flag, which makes it non-previewable (Apple does not allow execution of unsigned apps on iOS devices).

**Comment by adamkoch** [comment]
Some more background info:
```
$ shorebird --version                                                                            [11:51:00]
Shorebird 1.1.6 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.22.0 • revision 6d047e401941206daf11740c523ffa3364a2385b
Engine • revision c600950be82dcdad6a46da46bcc6e73773ca3907
```

`flutter devices` when testing the commands:
```
$ flutter devices                                                                                [11:51:59]
Found 5 connected devices:
  Adam’s iPhone (mobile)          • 00008130-[redacted]            • ios            • iOS 17.4.1 21E236
  iPhone 15 Pro (mobile)          • 2BBD350F-11FF-4FB0-B207-92D8724899CF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-5
  (simulator)
  macOS (desktop)                 • macos                                • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
  Mac Designed for iPad (desktop) • mac-designed-for-ipad                • darwin         • macOS 14.5 23F79 darwin-arm64
  Chrome (web)                    • chrome                               • web-javascript • Google Chrome 125.0.6422.113

No wireless devices were found.
```

Tested commands:
```
shorebird preview ios --device-id 00008130-[redacted]
shorebird preview --platform ios --device-id 00008130-[redacted]
shorebird preview ios --device-id 00008130-[redacted] --app-id 0f7a6dc6-bccc-4343-a208-3a63a9cb8b3f
```

All seem to result in Android build triggering:
```
$ shorebird preview --platform ios --device-id 00008130-[redacted]                         [11:42:47]
Which app flavor? prod
✓ Fetching releases (0.7s)
Which release would you like to preview? 1.2.44+1244
✓ Using production track (0.9s)
✓ Extracting metadata (0.2s)
✓ Building apks (4.4s)
✗ Exception: Failed to install apks: [BT:1.15.6] Error: No connected devices found.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: No connected devices found.
	at com.android.tools.build.bundletool.model.exceptions.InternalExceptionBuilder.build(InternalExceptionBuilder.java:57)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getTargetDevice(DeviceAnalyzer.java:160)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getAndValidateDevice(DeviceAnalyzer.java:133)
	at com.android.tools.build.bundletool.device.DeviceAnalyzer.getDeviceSpec(DeviceAnalyzer.java:55)
	at com.android.tools.build.bundletool.commands.InstallApksCommand.execute(InstallApksCommand.java:202)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:117)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:55)
 (0.3s)
```

**Comment by bryanoltman** [comment]
Investigation notes: it looks like the `runner` artifact is marked as non-sideloadable in our DB. Not totally sure how that happened, digging in now.

**Comment by adamkoch** [comment]
I wonder if it's related to an earlier problem I was having with flavors:
https://github.com/shorebirdtech/shorebird/issues/2004

**Comment by bryanoltman** [comment]
This would make sense if the app was released with the `--no-codesign` flag. We show a warning in the release output saying that the app won't be previewable, but we could probably improve messaging here to make it clearer what's happening.

**Comment by adamkoch** [comment]
Ah all makes sense! So WAI. I guess I will have to look at if i can stop using `--no-codesign` if I want to get previewing working. Thanks!
