### ISSUE TITLE
fix: shorebird build ipa fails with "Could not find an option named "dart-define".

### ISSUE THREAD

**Issue by jonasbark** [shorebirdtech/shorebird#2203]
Using Shorebird 1.1.9

**Steps To Reproduce**

1. attempt to build ipa using
`shorebird build ipa`

Fails with:
```
❯ shorebird build ipa
2024-06-05T17:56:43.530075 [WARN] Codesigning is disabled. You must manually codesign before deploying to devices.
2024-06-05T17:56:43.533255 Invalid argument(s): Could not find an option named "dart-define".
2024-06-05T17:56:43.533474 #0      ArgResults.wasParsed (package:args/src/arg_results.dart:146:7)
#1      ForwardedArgs.forwardedArgs (package:shorebird_cli/src/extensions/arg_results.dart:114:9)
#2      BuildIpaCommand.run (package:shorebird_cli/src/commands/build/build_ipa_command.dart:69:23)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#4      ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/shorebird_cli_command_runner.dart:197:20)
<asynchronous suspension>
#5      ShorebirdCliCommandRunner.run (package:shorebird_cli/src/shorebird_cli_command_runner.dart:124:14)
<asynchronous suspension>
#6      main.<anonymous closure> (file:///Users/boni/.shorebird/packages/shorebird_cli/bin/shorebird.dart:40:7)
<asynchronous suspension>
#7      main (file:///Users/boni/.shorebird/packages/shorebird_cli/bin/shorebird.dart:38:3)
<asynchronous suspension>

```

**Comment by eseidel** [comment]
Thank you for reporting.  Looks like a typo in our fix from yesterday.  FYI @bryanoltman Will have a fix for you shortly.

**Comment by bryanoltman** [comment]
I did not add these to the `shorebird build` commands. Can you tell us why you're running `shorebird build` instead of `shorebird release`?

**Comment by jonasbark** [comment]
Because I need to create an unsigned ipa file that I programmatically code sign afterwards

**Comment by bryanoltman** [comment]
You should use `shorebird release ios --no-codesign` if that's what you're after

**Comment by bryanoltman** [comment]
Context: without a release, you will not be able to patch the build generated with `shorebird build`

**Comment by jonasbark** [comment]
I'll revisit it, but back then I had to do it like this because I had a lot of trouble with iOS entitlements during that step.

Here's the full fastlane part:

```
sh("cd ../.. && shorebird build ipa")
          build_app(
            scheme: "Runner",
            export_method: "app-store",
            export_team_id: "...",
          )
          sh("mkdir -p ../../build/ios/ipa")
          sh("mv ../../ios/Runner.ipa ../../build/ios/ipa/fieldbots_app_flutter.ipa")
          sh("cd ../.. && shorebird release ios --no-codesign")
          upload_to_testflight(
            skip_waiting_for_build_processing: true,
            api_key: api_key,
            app_identifier: "io.fieldbots.app.test",
            ipa: "../build/ios/ipa/fieldbots_app_flutter.ipa",
          )
```

**Comment by bryanoltman** [comment]
I'm a little confused about the steps you're taking there. `shorebird build ipa` invokes the same build command as `shorebird release ios`. This should be as simple as:

```ruby
          sh("cd ../.. && shorebird release ios --no-codesign")
          upload_to_testflight(
            skip_waiting_for_build_processing: true,
            api_key: api_key,
            app_identifier: "io.fieldbots.app.test",
            ipa: "../build/ios/ipa/fieldbots_app_flutter.ipa",
          )
```

**Comment by jonasbark** [comment]
Just tried it and you are correct. The workarounds I had to use in earlier versions (as in several months ago) are no longer necessary.
