### ISSUE TITLE
fix: `shorebird` doesn't print anything when there is an invalid arg

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#2341]
This appears to only occur on main?
```
../_shorebird/shorebird/bin/shorebird --local-engine-src-path=$HOME/Documents/GitHub/engine/src --local-engine ios_release --local-engine-host host_release release ios-alpha

If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also file an issue if you think this is a bug. Please include the following log file in your report:
/Users/eseidel/Library/Application Support/shorebird/logs/1720718081424_shorebird.log
```

Seems the warning ends up as a .detail when it should be an .error, it shows up in verbose:
```
../_shorebird/shorebird/bin/shorebird --local-engine-src-path=$HOME/Documents/GitHub/engine/src --local-engine ios_release --local-engine-host host_release release ios-alpha --verbose
Invalid argument(s): Invalid platform: ios-alpha
#0      ReleaseTypeArgs.releaseTypes (package:shorebird_cli/src/release_type.dart:60:11)
#1      ReleaseCommand.run (package:shorebird_cli/src/commands/release/release_command.dart:145:17)
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#3      CompletionCommandRunner.runCommand (package:cli_completion/src/command_runner/completion_command_runner.dart:89:18)
#4      ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/shorebird_cli_command_runner.dart:202:32)
#5      ShorebirdCliCommandRunner.run.<anonymous closure> (package:shorebird_cli/src/shorebird_cli_command_runner.dart:129:19)
#6      _rootRun (dart:async/zone.dart:1399:13)
#7      _CustomZone.run (dart:async/zone.dart:1301:19)
#8      _runZoned (dart:async/zone.dart:1826:10)
#9      runZoned (dart:async/zone.dart:1763:10)
#10     runScoped (package:scoped_deps/src/scoped_deps.dart:64:10)
#11     ShorebirdCliCommandRunner.run (package:shorebird_cli/src/shorebird_cli_command_runner.dart:128:20)
#12     main.<anonymous closure>.<anonymous closure> (file:///Users/eseidel/Documents/GitHub/_shorebird/shorebird/packages/shorebird_cli/bin/shorebird.dart:41:49)
#13     _rootRun (dart:async/zone.dart:1399:13)
#14     _CustomZone.run (dart:async/zone.dart:1301:19)
#15     _runZoned (dart:async/zone.dart:1826:10)
#16     runZoned (dart:async/zone.dart:1763:10)
#17     runScoped (package:scoped_deps/src/scoped_deps.dart:64:10)
#18     main.<anonymous closure> (file:///Users/eseidel/Documents/GitHub/_shorebird/shorebird/packages/shorebird_cli/bin/shorebird.dart:40:13)
#19     _rootRun (dart:async/zone.dart:1399:13)
#20     _CustomZone.run (dart:async/zone.dart:1301:19)
#21     _runZoned (dart:async/zone.dart:1826:10)
#22     runZoned (dart:async/zone.dart:1763:10)
#23     IOOverrides.runZoned (dart:io/overrides.dart:146:10)
#24     main (file:///Users/eseidel/Documents/GitHub/_shorebird/shorebird/packages/shorebird_cli/bin/shorebird.dart:38:21)
#25     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#26     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

[Process.run] git symbolic-ref HEAD (in /Users/eseidel/Documents/GitHub/_shorebird/shorebird/bin/cache)
Exited with code 0

stdout:
refs/heads/main
```

```
../_shorebird/shorebird/bin/shorebird --version                                                                                                                                        
Shorebird 1.1.17 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.22.2 • revision 853d13d954df3b6e9c2f07b72062f33c52a9a64b
Engine • revision fb6b1af0c3f03aa2d60b8e176e915501e41116bb
```

my older install works:

```
%shorebird --version
Shorebird 1.1.6 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.22.0 • revision 6d047e401941206daf11740c523ffa3364a2385b
Engine • revision c600950be82dcdad6a46da46bcc6e73773ca3907
A new version of shorebird is available!
Run shorebird upgrade to upgrade.
%  shorebird --local-engine-src-path=$HOME/Documents/GitHub/engine/src --local-engine ios_release --local-engine-host host_release release ios-alpha                            
Invalid argument(s): Invalid platform: ios-alpha

If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also file an issue if you think this is a bug. Please include the following log file in your report:
/Users/eseidel/Library/Application Support/shorebird/logs/1720718128065_shorebird.log

```

**Comment by eseidel** [comment]
A reduction:
```
 ../_shorebird/shorebird/bin/shorebird ios-alpha

If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also file an issue if you think this is a bug. Please include the following log file in your report:
/Users/eseidel/Library/Application Support/shorebird/logs/1720718260988_shorebird.log

```

**Comment by bryanoltman** [comment]
One thing to keep in mind when fixing this is that we exit with some exceptions that we don't want to surface to the user. For example, when the user is prompted to continue and opts not to, a `UserCancelledException` is thrown. We don't want to log that.
