### ISSUE TITLE
fix: Cant get firebase messaging token (APNS token has not been set yet.)

### ISSUE THREAD

**Issue by mehdii08** [shorebirdtech/shorebird#2400]
App ID: 415b4011-84ed-4912-bcbf-21520ba9bd2e

I have implemented a Flutter app with 4 flavors. I ran the iOS project on my phone and iOS simulator and tested the FirebaseMessaging getToken() on Production flavor and its ok. When I create a release with shorebird and use it I face the error message:

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [firebase_messaging/apns-token-not-set] APNS token has not been set yet. Please ensure the APNS token is available by calling `getAPNSToken()`.
#0      MethodChannelFirebaseMessaging._APNSTokenCheck (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:138)
<asynchronous suspension>
#1      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:244)
<asynchronous suspension>
#2      LoginBiometricController._setDeviceId (package:careberry/pages/authentication/login_biometric/controller/login_biometric_controller.dart:140)
`

I think its not reproducable by you.

I expected to see the same behavior in my debug run with shorebird release to get Firebase Messaging token.

![Screenshot 2024-08-02 at 8 07 07 AM](https://github.com/user-attachments/assets/a1b1ac0d-df33-4c04-9501-52479ae91444)

**Comment by eseidel** [comment]
Sorry for the delay, this one appears to have slipped through the cracks.

Would love to help, but I don't know much about Firebase.  Does this occur when building with `flutter build` or only when building with `shorebird release`?

**Comment by bryanoltman** [comment]
@mehdii08 we'd love to help, but need more info. Let us know if you're able to try what @eseidel suggested above.

**Comment by eseidel** [comment]
Speculatively closing due to inactivity.  Please feel encouraged to comment again and we're happy to reopen!
