### ISSUE TITLE
Shorebird login will fail with error: FormatException: Invalid length, must be multiple of four (at character 104)

### ISSUE THREAD

**Issue by jonik-dev** [shorebirdtech/shorebird#2542]
```
shorebird --version
Shorebird 1.4.0 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.24.3 • revision 5a6dc546e8ecd01fe3b9527f082ff2d6864374f9
Engine • revision 033ec57900456ca7f8cd4bb59c2773a8ce27cb5d
```

```
shorebird login --verbose
FormatException: Invalid length, must be multiple of four (at character 104)
...***OBSCURED***...
                                                                              ^

#0      _Base64Decoder.close (dart:convert/base64.dart:639:7)
#1      Base64Decoder.convert (dart:convert/base64.dart:510:13)
#2      Base64Codec.decode (dart:convert/base64.dart:83:47)
#3      base64Decode (dart:convert/base64.dart:52:49)
#4      new CiToken.fromBase64 (package:shorebird_cli/src/auth/ci_token.dart:19:30)
#5      Auth._loadCredentials (package:shorebird_cli/src/auth/auth.dart:319:24)
#6      new Auth (package:shorebird_cli/src/auth/auth.dart:193:5)
#7      ScopedRef._value (package:scoped_deps/src/scoped_deps.dart:19:32)
#8      ScopedRef._value (package:scoped_deps/src/scoped_deps.dart)
#9      read (package:scoped_deps/src/scoped_deps.dart:47:60)
#10     auth (package:shorebird_cli/src/auth/auth.dart:31:18)
#11     LoginCommand.run (package:shorebird_cli/src/commands/login_command.dart:31:9)
#12     CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#13     CompletionCommandRunner.runCommand (package:cli_completion/src/command_runner/completion_command_runner.dart:89:18)
#14     ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/shorebird_cli_command_runner.dart:201:32)
#15     ShorebirdCliCommandRunner.run.<anonymous closure> (package:shorebird_cli/src/shorebird_cli_command_runner.dart:128:19)
#16     _rootRun (dart:async/zone.dart:1399:13)
#17     _CustomZone.run (dart:async/zone.dart:1301:19)
#18     _runZoned (dart:async/zone.dart:1826:10)
#19     runZoned (dart:async/zone.dart:1763:10)
#20     runScoped (package:scoped_deps/src/scoped_deps.dart:64:10)
#21     ShorebirdCliCommandRunner.run (package:shorebird_cli/src/shorebird_cli_command_runner.dart:127:20)
#22     main.<anonymous closure>.<anonymous closure> (file:///Users/mac/.shorebird/packages/shorebird_cli/bin/shorebird.dart:41:49)
#23     _rootRun (dart:async/zone.dart:1399:13)
#24     _CustomZone.run (dart:async/zone.dart:1301:19)
#25     _runZoned (dart:async/zone.dart:1826:10)
#26     runZoned (dart:async/zone.dart:1763:10)
#27     runScoped (package:scoped_deps/src/scoped_deps.dart:64:10)
#28     main.<anonymous closure> (file:///Users/mac/.shorebird/packages/shorebird_cli/bin/shorebird.dart:40:13)
#29     _rootRun (dart:async/zone.dart:1399:13)
#30     _CustomZone.run (dart:async/zone.dart:1301:19)
#31     _runZoned (dart:async/zone.dart:1826:10)
#32     runZoned (dart:async/zone.dart:1763:10)
#33     IOOverrides.runZoned (dart:io/overrides.dart:146:10)
#34     main (file:///Users/mac/.shorebird/packages/shorebird_cli/bin/shorebird.dart:38:21)
#35     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#36     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by felangel** [comment]
That looks like you’re using an old ci token. Do you have the SHOREBIRD_TOKEN env set? If so, I’d recommend re-generating a new ci token using the latest version of shorebird cli and trying again. Hope that helps!

**Comment by jonik-dev** [comment]
Yes I had SHOREBIRD_TOKEN env set. I removed that and re-generated new ci token. Now everything is working fine. Thank you.

**Comment by jonik-dev** [comment]
Yes I had SHOREBIRD_TOKEN env set. I removed that and re-generated new ci token. Now everything is working fine. Thank you.
