### ISSUE TITLE
Error on ios build

### ISSUE THREAD

**Issue by camillobucciarelli** [shorebirdtech/shorebird#2590]
**Description**

When I try to build ios app with command `shorebird release ios '--' --dart-define-from-file=.env/remote.json` I have the following error:
```
✓ Fetching apps (0.4s)
✗ Failed to build: [   +2 ms] Encountered error while archiving for device.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:722:7)
           <asynchronous suspension>
           #2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:427:50)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>


 (384.2s)
```

- Android app build correctly
- I built the ios app before, with the latest versions of flutter I can't build anymore

**Comment by bryanoltman** [comment]
At the end of the output, you should be given a path to a log file. Can you upload that file to this issue?

**Comment by sabreys** [comment]
we are having the same problem and it affected the pipeline. We are having problems with publishing processes.

**Comment by bryanoltman** [comment]
@sabreys As above, you should be given a path to a log file. Can you upload that file to this issue?

The output looks like:

```
If you aren't sure why this command failed, re-run with the --verbose flag to see more information.

You can also file an issue if you think this is a bug. Please include the following log file in your report:
/Users/bryanoltman/Library/Application Support/shorebird/logs/1730381568556_shorebird.log
```

**Comment by sabreys** [comment]
@bryanoltman 
[1730382909999_shorebird.log](https://github.com/user-attachments/files/17588664/1730382909999_shorebird.log)

until recently it was working automatically, but yesterday it started to fail like this. We haven't made any version changes.

**Comment by bryanoltman** [comment]
```
            ** ARCHIVE FAILED **


            The following build commands failed:
            	VerifyModule /Users/appcircle/Library/Developer/Xcode/DerivedData/Runner-cnmhwtielompgfcdacnyiuvhpkcr/Build/Intermediates.noindex/ArchiveIntermediates/stage/BuildProductsPath/Release-stage-iphoneos/device_info_plus/device_info_plus.framework (in target 'device_info_plus' from project 'Pods')
            	VerifyModule /Users/appcircle/Library/Developer/Xcode/DerivedData/Runner-cnmhwtielompgfcdacnyiuvhpkcr/Build/Intermediates.noindex/ArchiveIntermediates/stage/BuildProductsPath/Release-stage-iphoneos/package_info_plus/package_info_plus.framework (in target 'package_info_plus' from project 'Pods')
            (2 failures)
```

Seems like this is the issue.

I also noticed some cocoapods error logs earlier in the output:

```
           xcodebuild: error: Unable to read project 'Pods.xcodeproj' from folder '/Volumes/agent-disk/appcircle-runner/workflow_data/v04rh4rs.rb5/_appcircle_temp/Repository/ios/Pods'.
           	Reason: Project /Volumes/agent-disk/appcircle-runner/workflow_data/v04rh4rs.rb5/_appcircle_temp/Repository/ios/Pods/Pods.xcodeproj cannot be opened because it is missing its project.pbxproj file.
```
and
```
[   +2 ms] Error output from CocoaPods:
           ↳
[        ] 
               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.debug-prod.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.debug-prod.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).

               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.debug-sandbox.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.debug-sandbox.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).

               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.debug-highperf.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.debug-highperf.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).

               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.debug-dev.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.debug-dev.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).

               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.debug-stage.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.debug-stage.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).

               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.release-prod.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.release-prod.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.release-sandbox.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.release-sandbox.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.release-highperf.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.release-highperf.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.release-dev.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.release-dev.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.release-stage.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.release-stage.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile-prod.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile-prod.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile-sandbox.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile-sandbox.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile-highperf.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile-highperf.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile-dev.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile-dev.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile-stage.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile-stage.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

```

**Comment by camillobucciarelli** [comment]
> At the end of the output, you should be given a path to a log file. Can you upload that file to this issue?

Sorry for the delay, here the log file.
[1730650376103_shorebird.log.zip](https://github.com/user-attachments/files/17611166/1730650376103_shorebird.log.zip)

**Comment by bryanoltman** [comment]
```
/bin/sh -c /Users/cbucciarelli/Library/Developer/Xcode/DerivedData/Runner-dsnoxfwmlvjqxkepdhmitwkpspvd/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-98F3DBEF1D03EA9D5803F288.sh
/Users/cbucciarelli/Library/Developer/Xcode/DerivedData/Runner-dsnoxfwmlvjqxkepdhmitwkpspvd/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Script-98F3DBEF1D03EA9D5803F288.sh: line 5: flutterfire: command not found
```

It looks like `flutterfire` is not on the path of the machine being used to build

Also, this should give a better error message (https://github.com/shorebirdtech/shorebird/issues/2249)

**Comment by camillobucciarelli** [comment]
Yep, yesterday after thousands of hints I built the app with the following steps:

1. clean dart cache `dart pub cache clean`
2. reinstall flutterfire `dart pub global activate flutterfire_cli`
3. update shorebird (meanwhile a new release comes out) `shorebird upgrade`
4. update cocoapods to version 1.16.2 (I use homebrew) 
5. remove and recreate pod project and podfile.lock `pod install --repo-update` in the ios directory

after that the build was done successfully

I hope this helps someone else who has the same issue.
