### ISSUE TITLE
fix: too many open files

### ISSUE THREAD

**Issue by felangel** [shorebirdtech/shorebird#2697]
When running `shorebird release ios`, Customer reported:

```
2024-12-16T23:12:14.259242 No iOS release supplements found at /Users/builder/clone/build/ios/shorebird
2024-12-16T23:12:14.260492 ⠋ Uploading artifacts...
2024-12-16T23:12:17.994485 FileSystemException: Cannot open file, path = '/var/folders/w2/rrf5p87d1bbfyphxc7jdnyvh0000gn/T/ISo37l/Runner.xcarchive/dSYMs/Risk.framework.dSYM/Contents/Resources/Relocations/aarch64/Risk.yml' (OS Error: Too many open files, errno = 24)
```

Using `ulimit` to adjust the limit fixes the issue but this is tracking the work needed to ensure we close any open files.

**Comment by bryanoltman** [comment]
Another report from [Discord](https://discord.com/channels/1030243211995791380/1318547161184735232):

```
✓ Updating release status (0.3s)
⠋ Uploading artifacts...FileSystemException: Cannot open file, path = '/var/folders/8p/lh4h8fn16mzg46ndx9w_k6tw0000gp/T/Sn8St5/Runner.xcarchive/Products/Applications/Runner.app/Frameworks/App.framework/flutter_assets/packages/maple_common/assets/icons/fair.svg' (OS Error: Too many open files, errno = 24)
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      FileHandle.open (package:archive/src/util/_file_handle_io.dart:35:16)
#3      new FileHandle (package:archive/src/util/_file_handle_io.dart:18:7)
#4      new InputFileStream (package:archive/src/util/input_file_stream.dart:50:20)
#5      ZipFileEncoder.addFile (package:archive/src/io/zip_file_encoder.dart:136:24)
#6      ZipFileEncoder.addDirectory (package:archive/src/io/zip_file_encoder.dart:128:13)
#7      ZipFileEncoder.zipDirectory (package:archive/src/io/zip_file_encoder.dart:36:11)
#8      DirectoryArchive.zipToTempFile.<anonymous closure> (package:shorebird_cli/src/archive/directory_archive.dart:15:30)
#9      _RemoteRunner._run (dart:isolate:1098:47)
#10     _RemoteRunner._remoteExecute (dart:isolate:1092:12)
#11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
#12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
[Process.run] git symbolic-ref HEAD (in /Users/scotscriven/.shorebird/bin/cache)
Exited with code 0
```

**Comment by bryanoltman** [comment]
Seems to always be in the "uploading artifacts" step

**Comment by bryanoltman** [comment]
We only started getting reports of this starting in v1.5.0. We upgraded package:archive from major version 3 to 4, which might be the issue?

**Comment by felangel** [comment]
> We only started getting reports of this starting in v1.5.0. We upgraded package:archive from major version 3 to 4, which might be the issue?

Yeah that does seem suspicious. We could revert to the previous version but it'd be nice to reproduce.

**Comment by eseidel** [comment]
Another from Discord:
https://discord.com/channels/1030243211995791380/1084985149072080977/1318356128345755720

```
2024-12-16T23:12:14.259242 No iOS release supplements found at /Users/builder/clone/build/ios/shorebird
2024-12-16T23:12:14.260492 ⠋ Uploading artifacts...
2024-12-16T23:12:17.994485 FileSystemException: Cannot open file, path = '/var/folders/w2/rrf5p87d1bbfyphxc7jdnyvh0000gn/T/ISo37l/Runner.xcarchive/dSYMs/Risk.framework.dSYM/Contents/Resources/Relocations/aarch64/Risk.yml' (OS Error: Too many open files, errno = 24)
```

```
2024-12-16T23:12:17.994485 FileSystemException: Cannot open file, path = '/var/folders/w2/rrf5p87d1bbfyphxc7jdnyvh0000gn/T/ISo37l/Runner.xcarchive/dSYMs/Risk.framework.dSYM/Contents/Resources/Relocations/aarch64/Risk.yml' (OS Error: Too many open files, errno = 24)
2024-12-16T23:12:17.995041 #0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      FileHandle.open (package:archive/src/util/_file_handle_io.dart:35:16)
#3      new FileHandle (package:archive/src/util/_file_handle_io.dart:18:7)
#4      new InputFileStream (package:archive/src/util/input_file_stream.dart:50:20)
#5      ZipFileEncoder.addFile (package:archive/src/io/zip_file_encoder.dart:136:24)
#6      ZipFileEncoder.addDirectory (package:archive/src/io/zip_file_encoder.dart:128:13)
#7      ZipFileEncoder.zipDirectory (package:archive/src/io/zip_file_encoder.dart:36:11)
#8      DirectoryArchive.zipToTempFile.<anonymous closure> (package:shorebird_cli/src/archive/directory_archive.dart:15:30)
#9      _RemoteRunner._run (dart:isolate:1098:47)
#10     _RemoteRunner._remoteExecute (dart:isolate:1092:12)
#11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
#12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by eseidel** [comment]
We might have found the bug?  We had this code:
```
    await Isolate.run(
      () => ZipFileEncoder().zipDirectory(this, filename: outFile.path),
    );
 ```
Which was causing an unawaited future, potentially causing lots of open files concurrently when zipping things?

**Comment by felangel** [comment]
> We might have found the bug? We had this code:
> 
> ```
>     await Isolate.run(
>       () => ZipFileEncoder().zipDirectory(this, filename: outFile.path),
>     );
> ```
> 
> Which was causing an unawaited future, potentially causing lots of open files concurrently when zipping things?

Yup  `zipDirectory` used to be `sync` and became `async`.

**Comment by felangel** [comment]
filed: https://github.com/brendan-duncan/archive/issues/362
