### ISSUE TITLE
shorebird init throws a gradle Exception

### ISSUE THREAD

**Issue by esarbanis** [shorebirdtech/shorebird#453]
When I run `shorebird init` in the root of my flutter project but I get an error.

`shorebird doctor`:
```

Shorebird v0.1.0
Shorebird Engine • revision c415419390e4751ddfa3110e0808e7abb3d45a18
✓ AndroidManifest.xml files contain INTERNET permission (46ms)
✓ Shorebird is up-to-date (0.5s)
✓ Flutter install is correct (18.9s)

No issues detected!
```
`flutter doctor`:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.10, on Ubuntu 22.10 5.19.0-41-generic, locale
    en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.2)
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1)
[✓] VS Code
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

Error log:
```
Exception: To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.3/userguide/gradle_daemon.html#sec:disabling_the_daemon.

Could not write standard input to Gradle build daemon.
java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445)
	at java.base/java.io.OutputStream.write(OutputStream.java:162)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:68)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/7.3/userguide/gradle_daemon.html
Process command line: /usr/lib/jvm/java-18-openjdk-amd64/bin/java -XX:MaxPermSize=1024m -XX:MaxMetaspaceSize=1g --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xms512M -Xmx4g -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /home/efthymis/.gradle/wrapper/dists/gradle-7.3-all/dfe0rb4hnplvqkibhoc45how8/gradle-7.3/lib/gradle-launcher-7.3.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.3
Please read the following process output to find out more:
-----------------------
Unrecognized VM option 'MaxPermSize=1024m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by eseidel** [comment]
Thank you for the issue!  This is likely to be related to the flavor support we added last week.  It's trying to run gradle to get information about the flavors in your flutter project.
https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/shorebird_flavor_mixin.dart#L10

We should be able to have a fix for you later today.

**Comment by esarbanis** [comment]
That's awesome! Thanks @eseidel

**Comment by eseidel** [comment]
Apologies, I didn't get to this today (and I may not tomorrow, we may be at an offsite).  But we should be able to get this done by EOD Weds.  Thanks for filing and thanks for your patience.

**Comment by esarbanis** [comment]
How can I help with this? WIth a few pointers I can issue a PR

**Comment by felangel** [comment]
Hi @esarbanis 👋 
Sorry for the delayed response! Can you provide a bit more information regarding your Android Studio installation locations? Also, do you already have `JAVA_HOME` set on your environment? Thanks and sorry for the inconvenience!

**Comment by esarbanis** [comment]
Hey @felangel, thanks for stepping in.

```bash
$> which android-studio
/snap/bin/android-studio
```

`JAVA_HOME` is not set.

**Comment by eseidel** [comment]
We should be able to get this done shortly.  By the way, we're all on discord: discord.gg/shorebird if like to be able to discuss in realtime.

**Comment by felangel** [comment]
> Hey @felangel, thanks for stepping in.
> 
> ```shell
> $> which android-studio
> /snap/bin/android-studio
> ```
> 
> `JAVA_HOME` is not set.

Thanks so much! As Eric mentioned, we'll work on getting this fixed today 👍
