### ISSUE TITLE
feat: Would like better usage information for `aar` missing option

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#982]
```
PS C:\Users\micro\Documents\GitHub\samples\add_to_app\my_flutter_module> shorebird release aar
Unhandled exception:
Invalid argument(s): Option release-version is mandatory.
#0      ArgResults.[] (package:args/src/arg_results.dart:70:7)
#1      ReleaseAarCommand.run (package:shorebird_cli/src/commands/release/release_aar_command.dart:91:35)
<asynchronous suspension>
#2      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#3      ShorebirdCliCommandRunner.runCommand (package:shorebird_cli/src/command_runner.dart:151:18)
<asynchronous suspension>
#4      ShorebirdCliCommandRunner.run (package:shorebird_cli/src/command_runner.dart:93:14)
<asynchronous suspension>
#5      main (file:///C:/Users/micro/.shorebird/packages/shorebird_cli/bin/shorebird.dart:24:5)
<asynchronous suspension>
```

Probably don't need the back-trace and would be good to have an example of what it's asking for. 🤷

**Comment by garrettApproachableGeek** [comment]
Addressed by https://github.com/shorebirdtech/shorebird/pull/2003, likely should be closed

Example output from shorebird 1.5.3
```
shorebird release aar       
Missing required argument: --release-version

If you aren't sure why this command failed, re-run with the --verbose flag to see more information.
```
